apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-calculator-deployment
  labels:
    app: django-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-calculator
  template:
    metadata:
      labels:
        app: django-calculator
    spec:
      containers:
      - name: calculator-container
        #  Replace this with your actual ECR image URI
        image: .dkr.ecr.us-east-1.amazonaws.com/django-calculator-app:latest
        ports:
        - containerPort: 8000
