apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-calculator-deployment
  labels:
    app: django-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-calculator
  template:
    metadata:
      labels:
        app: django-calculator
    spec:
      containers:
      - name: calculator-container
        # CRITICAL: Replace this with your actual ECR image URI from Step 1
        image: 239002030585.dkr.ecr.us-east-1.amazonaws.com/django-calculator-app:latest
        ports:
        - containerPort: 8000
